2025-04-29 01:58:47.782 | INFO     | utils.logger:<module>:32 - Log folder created at: logs
2025-04-29 01:58:47.785 | INFO     | utils.logger:<module>:39 - Logging to file: logs/project_log.log
2025-04-29 01:58:47.789 | INFO     | utils.config:<module>:15 - Loaded .env from /home/denisecase/repos/pro-analytics-ai/backend/utils/../../.env
/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py:896: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py:896: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/auto_gptq/nn_modules/triton_utils/kernels.py:410: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd
/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/auto_gptq/nn_modules/triton_utils/kernels.py:418: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @custom_bwd
/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/auto_gptq/nn_modules/triton_utils/kernels.py:461: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd(cast_inputs=torch.float16)
Traceback (most recent call last):
  File "/home/denisecase/repos/pro-analytics-ai/.venv/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 413, in main
    run(
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 580, in run
    server.run()
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 70, in serve
    await self._serve(sockets)
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 77, in _serve
    config.load()
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/uvicorn/config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/denisecase/repos/pro-analytics-ai/backend/A_api_interface/query_api.py", line 35, in <module>
    from backend.B_prompt_model.b0_pipeline import query  
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/backend/B_prompt_model/b0_pipeline.py", line 24, in <module>
    from backend.B_prompt_model.b2_call_model import call_model
  File "/home/denisecase/repos/pro-analytics-ai/backend/B_prompt_model/b2_call_model.py", line 98, in <module>
    client, model, tokenizer = load_8bit_model()
                               ^^^^^^^^^^^^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/backend/B_prompt_model/b2_call_model.py", line 69, in load_8bit_model
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3044, in from_pretrained
    hf_quantizer = AutoHfQuantizer.from_config(config.quantization_config, pre_quantized=pre_quantized)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/transformers/quantizers/auto.py", line 124, in from_config
    return target_cls(quantization_config, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/transformers/quantizers/quantizer_gptq.py", line 47, in __init__
    from optimum.gptq import GPTQQuantizer
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/optimum/gptq/__init__.py", line 15, in <module>
    from .quantizer import GPTQQuantizer, load_quantized_model
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/optimum/gptq/quantizer.py", line 53, in <module>
    from auto_gptq import __version__ as autogptq_version
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/auto_gptq/__init__.py", line 3, in <module>
    from .utils.peft_utils import get_gptq_peft_model
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/auto_gptq/utils/peft_utils.py", line 6, in <module>
    from peft import PeftConfig, PeftModel, PeftType, get_peft_model
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/peft/__init__.py", line 17, in <module>
    from .auto import (
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/peft/auto.py", line 32, in <module>
    from .peft_model import (
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/peft/peft_model.py", line 37, in <module>
    from transformers import Cache, DynamicCache, EncoderDecoderCache, PreTrainedModel
ImportError: cannot import name 'EncoderDecoderCache' from 'transformers' (/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/transformers/__init__.py)
2025-04-29 02:02:34.756 | INFO     | utils.logger:<module>:32 - Log folder created at: logs
2025-04-29 02:02:34.759 | INFO     | utils.logger:<module>:39 - Logging to file: logs/project_log.log
2025-04-29 02:02:34.762 | INFO     | utils.config:<module>:15 - Loaded .env from /home/denisecase/repos/pro-analytics-ai/backend/utils/../../.env
/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py:896: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py:896: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/auto_gptq/nn_modules/triton_utils/kernels.py:410: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd
/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/auto_gptq/nn_modules/triton_utils/kernels.py:418: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @custom_bwd
/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/auto_gptq/nn_modules/triton_utils/kernels.py:461: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd(cast_inputs=torch.float16)
Traceback (most recent call last):
  File "/home/denisecase/repos/pro-analytics-ai/.venv/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 413, in main
    run(
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 580, in run
    server.run()
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 70, in serve
    await self._serve(sockets)
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 77, in _serve
    config.load()
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/uvicorn/config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/denisecase/repos/pro-analytics-ai/backend/A_api_interface/query_api.py", line 36, in <module>
    from backend.B_prompt_model.b0_pipeline import query  
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/backend/B_prompt_model/b0_pipeline.py", line 24, in <module>
    from backend.B_prompt_model.b2_call_model import call_model
  File "/home/denisecase/repos/pro-analytics-ai/backend/B_prompt_model/b2_call_model.py", line 98, in <module>
    client, model, tokenizer = load_8bit_model()
                               ^^^^^^^^^^^^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/backend/B_prompt_model/b2_call_model.py", line 69, in load_8bit_model
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3044, in from_pretrained
    hf_quantizer = AutoHfQuantizer.from_config(config.quantization_config, pre_quantized=pre_quantized)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/transformers/quantizers/auto.py", line 124, in from_config
    return target_cls(quantization_config, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/transformers/quantizers/quantizer_gptq.py", line 47, in __init__
    from optimum.gptq import GPTQQuantizer
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/optimum/gptq/__init__.py", line 15, in <module>
    from .quantizer import GPTQQuantizer, load_quantized_model
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/optimum/gptq/quantizer.py", line 53, in <module>
    from auto_gptq import __version__ as autogptq_version
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/auto_gptq/__init__.py", line 3, in <module>
    from .utils.peft_utils import get_gptq_peft_model
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/auto_gptq/utils/peft_utils.py", line 6, in <module>
    from peft import PeftConfig, PeftModel, PeftType, get_peft_model
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/peft/__init__.py", line 17, in <module>
    from .auto import (
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/peft/auto.py", line 32, in <module>
    from .peft_model import (
  File "/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/peft/peft_model.py", line 37, in <module>
    from transformers import Cache, DynamicCache, EncoderDecoderCache, PreTrainedModel
ImportError: cannot import name 'EncoderDecoderCache' from 'transformers' (/home/denisecase/repos/pro-analytics-ai/.venv/lib/python3.11/site-packages/transformers/__init__.py)
